# Site settings
baseurl = "http://www.catalyteek.com/"
languageCode = "en-us"
title = "Hugo Freelancer Theme"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Catalyteek"
    description = "Catalyteek Homepage"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "laurent@catalyteek.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Catalyteek"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Laurent VAYLET"
        subtitle = "MLOps | DataOps | DevOps | 2x GCP Certified Professional (Cloud Architect + Data Engineer)"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 
        # 'data' directory at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About Me"
        # The about text is splitted into a left and right column
        left = "A true passionate of everything related to cloud, infrastructure, DevOps and automation, I like to use my software engineering skills to make everyone's life easier. I collaborate with my customers to uncover their needs and identify the most efficient solutions, with an emphasis on hiding complexity and reducing time-to-market while making maintenance easy at the same time."
        right = "Proactive and curious, I love to learn new skills on a daily basis and I embrace change whenever it shows up. In spite of being very open to new ideas, I am very strict and uncompromising when it comes to writing clean code and documenting my work. Finally, as a big fan of open source in general, I would rather reuse existing components than reinvent the wheel."

        [params.about.button]
            text = "My full profile"
            link = "//linkedin.com/in/laurent-vaylet-66b49a5/"
            icon = "linkedin"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Address"
            # Postal address (add as many lines as necessary)
            address = ["8 Parc de la Bérengère", "92210 Saint-Cloud"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/catalyteek"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/in/laurent-vaylet-66b49a5/"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
